sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codacy-coverage
script: py.test --cov=swimlane --cov-report=xml .
after_script: python-codacy-coverage -r coverage.xml
